### ISSUE TITLE
New version v.0.21.0 does not work

### ISSUE THREAD

**Issue by EstiGascon** [esowc/ecPoint-Calibrate#151]
Augustin and I had the same error when we used the new software. Any time that we tried to change any option or load any database, we have the error of :

**"empty response from server"**

It is also important to point out that when we run the software in the terminal, it is opened properly, but we have an error message:

**Digest: sha256:fd12feb48a1aca783c15e50776a5f925eec5dee9fdc7762ff21701ab33db7ff0

Status: Downloaded newer image for onyb/ecpoint-calibrate-core:0.21.0

Running Docker container: image=onyb/ecpoint-calibrate-core:0.21.0 containerID=bf1c1797fad2

Error loading Metview/libMvMacro. LD_LIBRARY_PATH=/opt/conda/lib/metview-bundle/lib:

Traceback (most recent call last):

  File "/app/.venv/lib/python3.8/site-packages/metview/bindings.py", line 182, in <module>

    lib = ffi.dlopen(os.path.join(mv_lib, "libMvMacro.so"))

  File "/app/.venv/lib/python3.8/site-packages/cffi/api.py", line 150, in dlopen

    lib, function_cache = _make_ffi_library(self, name, flags)

  File "/app/.venv/lib/python3.8/site-packages/cffi/api.py", line 832, in _make_ffi_library

    backendlib = _load_backend_lib(backend, libname, flags)

  File "/app/.venv/lib/python3.8/site-packages/cffi/api.py", line 827, in _load_backend_lib

    raise OSError(msg)

OSError: cannot load library '/opt/conda/lib/metview-bundle/lib/libMvMacro.so': /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/conda/lib/metview-bundle/lib/libMvMacro.so).  Additionally, ctypes.util.find_library() did not manage to locate a library called '/opt/conda/lib/metview-bundle/lib/libMvMacro.so'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code

    exec(code, run_globals)

  File "/app/core/api.py", line 15, in <module>

    from core.loaders import geopoints as geopoints_loader

  File "/app/core/loaders/geopoints.py", line 4, in <module>

    import metview

  File "/app/.venv/lib/python3.8/site-packages/metview/__init__.py", line 26, in <module>

    from . import bindings as _bindings

  File "/app/.venv/lib/python3.8/site-packages/metview/bindings.py", line 192, in <module>

    raise exp

  File "/app/.venv/lib/python3.8/site-packages/metview/bindings.py", line 185, in <module>

    lib = ffi.dlopen(os.path.join(mv_lib, "libMvMacro"))

  File "/app/.venv/lib/python3.8/site-packages/cffi/api.py", line 150, in dlopen

    lib, function_cache = _make_ffi_library(self, name, flags)

  File "/app/.venv/lib/python3.8/site-packages/cffi/api.py", line 832, in _make_ffi_library

    backendlib = _load_backend_lib(backend, libname, flags)

  File "/app/.venv/lib/python3.8/site-packages/cffi/api.py", line 827, in _load_backend_lib

    raise OSError(msg)

OSError: cannot load library '/opt/conda/lib/metview-bundle/lib/libMvMacro': /opt/conda/lib/metview-bundle/lib/libMvMacro: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/opt/conda/lib/metview-bundle/lib/libMvMacro'

PythonServe - FATAL  - 20210225.133155 - Signal 1 received**

**Comment by onyb** [comment]
@EstiGascon Can you please try opening the GUI again? I have updated the faulty Docker image.

**Comment by EstiGascon** [comment]
Now it works! Many thanks @onyb
